---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.serviceName}}
spec:
  selector:
    app: {{.Values.serviceName}}
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{.Values.serviceName}}
spec:
  selector:
    matchLabels:
      app: {{.Values.serviceName}}
      tier: frontend
      track: stable
  replicas:  {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{.Values.serviceName}}
        tier: frontend
        track: stable
    spec:
      containers:
      - name: {{.Values.serviceName}}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: REACT_APP_BACKEND_URL
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
