---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.serviceName}}
spec:
  selector:
    matchLabels:
      app: {{.Values.serviceName}}
      tier: backend
      track: stable
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{.Values.serviceName}}
        tier: backend
        track: stable
    spec:
      containers:
        - name: {{.Values.serviceName}}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9000
---

apiVersion: v1
kind: Service
metadata:
  name: {{.Values.serviceName}}
  labels:
    app: {{.Values.serviceName}}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 9000
  selector:
    app: {{.Values.serviceName}}
